### ISSUE TITLE
Write down Task list

### ISSUE THREAD

**Issue by assemble-gear-dog** [assemble-gear-dog/git-tutorial#2]
# _Task to complete this month (Demo)_

- [ ]  Complete image processing
- [ ]  Set the deployment tool
- [ ]  Implement lottery function

＜日本語でもOK！＞

- [x] 画像イメージを加工処理する
- [ ] デプロイスケジュールを確認する
- [ ] Webアプリのテスト
